Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2022-09, with the labels that each got.

#127 fix e2e tests labeled with 'cluster-upgrade-conformance'
  Makefile
  controllers/nutanixmachine_controller.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-scale-in/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades/nmt.yaml
Labels: ignore-for-release

#129 Modify Calico e2e Yaml manifests
  test/e2e/data/cni/calico/calico.yaml
Labels: ignore-for-release

#139 fixed the data format to fit regex format
  controllers/nutanixmachine_controller.go
Labels: bug

#146 Update go version from 1.17 to 1.19
  .github/workflows/build-dev.yaml
  .github/workflows/release.yaml
  .github/workflows/synopsys-schedule.yaml
  .github/workflows/synopsys.yaml
  .github/workflows/trivy-scan.yaml
  go.mod
  go.sum
Labels: dependencies

#145 Update makefile with a release-manifests target
  .github/workflows/release.yaml
  .gitignore
  Makefile
Labels: ignore-for-release

#138 add link to badges
  README.md
Labels: ignore-for-release

#147 Feat/secret format alignment
  Makefile
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/manager/manager.yaml
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  controllers/suite_test.go
  go.mod
  go.sum
  main.go
  pkg/client/client.go
  pkg/client/state.go
  pkg/context/context.go
  templates/base/cluster-template.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  test/e2e/categories_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/bases/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-credential-ref/nc.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster/nc.yaml
  test/e2e/multi_nic_test.go
  test/e2e/nutanix_client.go
  test/e2e/nutanix_client_test.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
Labels: enhancement
