Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2022-05, with the labels that each got.

#27 adding conditions to nutanixcluster and nutanixmachine resources
  api/v1alpha4/conditions.go
  api/v1beta1/conditions.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
Labels: enhancement

#30 add BlackDuck scan
  .github/workflows/synopsys.yaml
Labels: ignore-for-release

#32 fix klog.Info to display parameters correctly
  controllers/helpers.go
Labels: bug

#28 Feat/secret mgmt
  api/v1alpha4/conditions.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/conditions.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/zz_generated.deepcopy.go
  cluster-template.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/manager/manager.yaml
  config/rbac/role.yaml
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  pkg/client/client.go
Labels: enhancement

#33 implement additional kube-vip settings
  cluster-template.yaml
  clusterctl.yaml
  docs/getting_started.md
Labels: enhancement
