Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2022-12, with the labels that each got.

#179 Update kube-vip to v0.5.7
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: enhancement

#183 fix base64 line wrapping
  scripts/gen-self-cert.sh
Labels: bug

#189 refactor nutanixcluster controller
  controllers/nutanixcluster_controller.go
Labels: bug

#190 Add uuid cluster creation testing and capxhelpers
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
  main.go
  test/e2e/basic_uuid_test.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
Labels: ignore-for-release
