Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2022-08, with the labels that each got.

#91 Add option to run e2e tests using Cilium
  Makefile
  test/e2e/README.md
  test/e2e/data/cni/cilium/cilium.yaml
Labels: ignore-for-release

#90 Add option to run e2e tests using Flannel
  Makefile
  test/e2e/README.md
  test/e2e/data/cni/flannel/flannel.yaml
Labels: ignore-for-release

#94 fix copyright
  api/v1alpha4/conditions.go
  api/v1alpha4/doc.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/nutanix_types.go
  api/v1alpha4/nutanixcluster_conversion.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_conversion.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/nutanixmachinetemplate_conversion.go
  api/v1alpha4/nutanixmachinetemplate_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/conditions.go
  api/v1beta1/doc.go
  api/v1beta1/groupversion_info.go
  api/v1beta1/nutanix_types.go
  api/v1beta1/nutanixcluster_conversion.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixmachine_conversion.go
  api/v1beta1/nutanixmachine_types.go
  api/v1beta1/nutanixmachinetemplate_conversion.go
  api/v1beta1/nutanixmachinetemplate_types.go
  api/v1beta1/zz_generated.deepcopy.go
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  controllers/suite_test.go
  deployments/entrypoint.sh
  deployments/local.sh
  hack/boilerplate.go.txt
  hooks/build-finalize.sh
  main.go
  pkg/client/client.go
  pkg/client/state.go
  pkg/context/context.go
  scripts/gen-self-cert.sh
  test/e2e/categories_test.go
  test/e2e/multi_nic_test.go
  test/e2e/nutanix_client.go
  test/e2e/nutanix_client_test.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
  tools/imagebuilder/create_image_build.sh
  tools/imagebuilder/delete_image_build_vm.sh
  tools/imagebuilder/terraform/scripts/build_os_image.sh
  tools/imagebuilder/terraform/scripts/install_prerequisites.sh
Labels: ignore-for-release

#97 add Remove Cluster Section to Getting Started Doc
  docs/getting_started.md
Labels: documentation

#96 adapt CPU & Memory resources settings
  config/default/manager_auth_proxy_patch.yaml
  config/manager/manager.yaml
Labels: enhancement

#99 Fix CVEs CVE-2022-21698 CVE-2022-27191
  go.mod
  go.sum
Labels: dependencies

#98 Implement Trivy scan
  .github/workflows/build-dev.yaml
  .github/workflows/trivy-scan.yaml
Labels: ignore-for-release

#100 scan builded image
  .github/workflows/trivy-scan.yaml
Labels: ignore-for-release

#101 replace REPOSITORY_NAME
  .github/workflows/trivy-scan.yaml
Labels: ignore-for-release

#92 initial checkin to run ci-e2e
  Makefile
  hack/ensure-go.sh
  hack/install-go.sh
  scripts/ci-e2e.sh
Labels: ignore-for-release

#104 Update ccm flavor
  scripts/ccm_nutanix_update.sh
  templates/ccm/kustomization.yaml
  templates/ccm/nutanix-ccm-crs.yaml
  templates/ccm/nutanix-ccm-secret.yaml
  templates/ccm/nutanix-ccm.yaml
  templates/cluster-template-ccm.yaml
Labels: enhancement

#123 add machine templates and configuration for health-remediation e2e tests
  Makefile
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation/md.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation/mhc.yaml
  test/e2e/mhc_remediations_test.go
Labels: ignore-for-release

#124 Fix e2e test for non-existing project
  test/e2e/test_helpers.go
Labels: ignore-for-release
