Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2022-10, with the labels that each got.

#152 prepare for 1.0 GA release
  .github/workflows/release.yaml
  metadata.yaml
Labels: ignore-for-release

#141 Add CSI e2e tests
  Makefile
  test/e2e/config/nutanix.yaml
  test/e2e/csi_test.go
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kct.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kustomization.yaml
  test/e2e/e2e_suite_test.go
Labels: ignore-for-release

#153 modified nutanix.yaml for 1.0.0 release
  test/e2e/config/nutanix.yaml
Labels: ignore-for-release

#154 Add developer workflow docs
  README.md
  docs/developer_workflow.md
Labels: ignore-for-release

#162 modified e2e to use templates/base yamls
  templates/base/cluster-with-kcp.yaml
  templates/base/kustomization.yaml
  templates/base/md.yaml
  templates/base/mhc.yaml
  templates/base/nmt.yaml
  templates/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/base/crs.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-additional-categories/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-ccm/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-scale-in/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nmt/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-secret/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-project/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template/kustomization.yaml
Labels: ignore-for-release

#163 fix cve 2022-32149
  go.mod
  go.sum
Labels: dependencies

#161 cluster template improvements
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: enhancement

#167 fix issue where status is not updates on machines after move operation
  api/v1beta1/conditions.go
  controllers/helpers.go
  controllers/nutanixmachine_controller.go
  go.mod
Labels: ignore-for-release
