Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2023-12, with the labels that each got.

#335 first version of failure domain support for CAPX
  Makefile
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/conditions.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixmachine_types.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachinetemplates.yaml
  controllers/helpers.go
  controllers/helpers_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-failure-domains/failure-domain-nmt.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-failure-domains/failure-domain-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-failure-domains/kustomization.yaml
  test/e2e/failure_domains_test.go
  test/e2e/test_helpers.go
Labels: enhancement, lgtm, approved

#340 Enhance ownerReferences for Secrets used by CAPX
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixmachine_types.go
  api/v1beta1/nutanixmachinetemplate_types.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
Labels: enhancement, lgtm, approved

#346 build: gitingore .env and .envrc files
  .gitignore
Labels: lgtm, approved

#331 Make CCM for CAPX mandatory by default
  Makefile
  api/v1alpha4/nutanixmachine_types.go
  api/v1beta1/nutanixmachine_types.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  hack/install-go.sh
  metadata.yaml
  scripts/ccm_nutanix_update.sh
  templates/base/ccm-patch.yaml
  templates/base/kustomization.yaml
  templates/base/nutanix-ccm-crs.yaml
  templates/base/nutanix-ccm-secret.yaml
  templates/base/nutanix-ccm.yaml
  templates/ccm/kustomization.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  test/e2e/basic_uuid_test.go
  test/e2e/ccm_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/ccm-update.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cm.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/md.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/nmt.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-ccm/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-failure-domains/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-kcp-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-md-remediation/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nmt/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-nutanix-cluster/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-no-secret/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-project/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-upgrades/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/no-kubeproxy/cluster-template-ccm/kustomization.yaml
  test/e2e/log/log.go
Labels: lgtm, approved

#345 style: dev docs changes
  .gitignore
  Makefile
  clusterctl.yaml
  clusterctl.yaml.tmpl
  docs/developer_workflow.md
Labels: lgtm, approved

#350 Reflect deprecation of .status.nodeRef in the NutanixMachine CRD
  .github/workflows/build-dev.yaml
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
Labels: ok-to-test, lgtm, approved
