Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2023-02, with the labels that each got.

#208 Change default max-concurrent-reconciles to 10
  Makefile
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
  controllers/options.go
  controllers/options_test.go
  go.mod
  main.go
  test/e2e/md_scale_test.go
Labels: enhancement

#215 migrate to registry.k8s.io
  templates/cluster-template-csi.yaml
  templates/csi/nutanix-csi-snapshot.yaml
  templates/csi/nutanix-csi-storage.yaml
Labels: enhancement

#216 update kube-vip to v0.5.9
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: dependencies

#224 update kube-vip to 0.5.10
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: bug, dependencies

#227 update go.mod with capi 1.3.3 dependencies
  go.mod
  go.sum
Labels: ignore-for-release

#232 e2e update calico to 3.25
  test/e2e/data/cni/calico/calico.yaml
Labels: ignore-for-release
