Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2023-01, with the labels that each got.

#197 inject hostname through metadata
  controllers/nutanixmachine_controller.go
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kct.yaml
Labels: enhancement

#198 update CAPI version for e2e tests
  test/e2e/config/nutanix.yaml
  test/e2e/data/shared/metadata.yaml
Labels: ignore-for-release

#199 update golang.org/x/net@0.4.0 fix CVE-2022-41721
  go.mod
  go.sum
Labels: dependencies, go

#203 update kube-vip to 0.5.8
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: dependencies

#207 enable CustomLabeling in CCM flavor
  templates/ccm/nutanix-ccm.yaml
  templates/cluster-template-ccm.yaml
Labels: enhancement
