Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2023-08, with the labels that each got.

#304 Check nutanixmachine resources when deleting nutanixcluster
  controllers/nutanixcluster_controller.go
Labels: bug, lgtm, approved

#306 update kube-vip to v0.6.2
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: dependencies, lgtm

#309 increase log stacktrace default level to panic
  config/default/manager_auth_proxy_patch.yaml
Labels: lgtm, approved

#308 add error return when category value cannot be created
  controllers/helpers.go
Labels: lgtm, approved
