Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2023-04, with the labels that each got.

#266 Update CAPI e2e components to v1.4.1
  test/e2e/config/nutanix.yaml
Labels: ignore-for-release

#268 update kube-vip to v0.5.12
  templates/base/cluster-with-kcp.yaml
  templates/cluster-template-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: dependencies, lgtm

#267 remove klog dependency
  Makefile
  config/default/manager_auth_proxy_patch.yaml
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
  go.mod
  go.sum
  main.go
  pkg/client/client.go
  pkg/client/state.go
  pkg/context/context.go
Labels: lgtm
