Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-04, with the labels that each got.

#396 Add variable for setting the additional categories on cluster
  templates/cluster-template-clusterclass.yaml
  templates/clusterclass/clusterclass.yaml
  templates/template_test.go
  templates/testdata/cluster-with-additional-categories.yaml
Labels: lgtm, approved

#402 fix: set the kube-vip var to default value instead of env for clusterclass
  templates/cluster-template-clusterclass.yaml
  templates/clusterclass/kcpt.yaml
Labels: lgtm, approved

#397 Add variable for setting the GPUs on cluster
  templates/cluster-template-clusterclass.yaml
  templates/clusterclass/clusterclass.yaml
  templates/template_test.go
  templates/testdata/cluster-with-gpu.yaml
Labels: lgtm, approved

#404 Update additionalCategories clusterclass patch to target controlplane and workers separately
  templates/cluster-template-clusterclass.yaml
  templates/clusterclass/clusterclass.yaml
  templates/testdata/cluster-with-additional-categories.yaml
Labels: lgtm, approved

#407 Update release artifact workflow
  .github/workflows/release.yaml
Labels: lgtm, approved

#403 Ensure fallback config is read only when prismCentral is absent
  pkg/client/client.go
  pkg/client/client_test.go
Labels: lgtm, approved

#409 Cherry-pick PR #360 and #403 to release-v1.3
  .github/workflows/build-dev.yaml
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/testdata/invalidTestConfigMissingCredentialRef.json
  pkg/client/testdata/validTestCA.pem
  pkg/client/testdata/validTestConfig.json
  pkg/client/testdata/validTestCredentials.json
  pkg/client/testdata/validTestManagerCA.pem
  pkg/client/testdata/validTestManagerCredentials.json
  test/e2e/nutanix_client.go
Labels: lgtm, approved

#406 Add a provision for handling image based bootstrap
  api/v1beta1/nutanixmachine_types.go
  controllers/nutanixmachine_controller.go
Labels: lgtm, approved

#400 removed optional annotation from non-optional fields
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclustertemplates.yaml
  controllers/helpers_test.go
  controllers/nutanixcluster_controller_test.go
Labels: lgtm, approved, breaking-change

#414 Revert "removed optional annotation from non-optional fields (#400)"
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclustertemplates.yaml
  controllers/helpers_test.go
  controllers/nutanixcluster_controller_test.go
Labels: lgtm

#416 Explicitly set a rate limiter for controller config
  controllers/options.go
  controllers/options_test.go
  main.go
  main_test.go
Labels: lgtm, approved

#410 use latest version of capx in template-tests
  go.mod
  templates/template_test.go
Labels: lgtm, approved

#422 added modular tests for cluster with topology for all supported k8s v…
  test/e2e/capx_quick_start_test.go
  test/e2e/cluster_topology.go
  test/e2e/cluster_topology_basic_test.go
  test/e2e/cluster_topology_conformance_test.go
  test/e2e/cluster_topology_mega_scale_test.go
  test/e2e/cluster_topology_scale_in_test.go
  test/e2e/cluster_topology_scale_out_test.go
  test/e2e/cluster_topology_scale_up_down_test.go
  test/e2e/cluster_topology_upgrade_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterclass_changes_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/test_helpers.go
Labels: lgtm, approved
