Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-07, with the labels that each got.

#451 Add Github action for E2E tests
  .github/workflows/build-dev.yaml
  .github/workflows/e2e.yaml
  .github/workflows/synopsys.yaml
  Makefile
  devbox.json
  devbox.lock
  hack/kind/dns-override.yaml
  scripts/ci-e2e.sh
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cm.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/md.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/nmt.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/ccm-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cm.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/md.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nmt.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm-crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm-secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.5/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.5/base/controlplane-vip.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.5/base/crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.5/cluster-template/kustomization.yaml
  test/e2e/data/shared/metadata.yaml
  test/e2e/e2e_suite_test.go
Labels: ignore-for-release

#453 Remove v1alpha4 CRDs, types and associated code
  Makefile
  PROJECT
  api/v1alpha4/conditions.go
  api/v1alpha4/doc.go
  api/v1alpha4/groupversion_info.go
  api/v1alpha4/nutanix_types.go
  api/v1alpha4/nutanixcluster_conversion.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_conversion.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/nutanixmachinetemplate_conversion.go
  api/v1alpha4/nutanixmachinetemplate_types.go
  api/v1alpha4/v1alpha4_test.go
  api/v1alpha4/zz_generated.conversion.go
  api/v1alpha4/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachinetemplates.yaml
  config/crd/kustomization.yaml
  main.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/cm.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/md.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/no-kubeproxy/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/no-kubeproxy/no-kubeproxy.yaml
Labels: breaking-change

#457 fix blackduck token key
  .github/workflows/synopsys-schedule.yaml
  .github/workflows/synopsys.yaml
Labels: ignore-for-release

#458 Update E2E CNI Manifests
  .gitignore
  Makefile
  devbox.json
  devbox.lock
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/cni/cilium/cilium-no-kubeproxy.yaml
  test/e2e/data/cni/cilium/cilium.yaml
  test/e2e/data/cni/flannel/flannel.yaml
  test/e2e/data/cni/kindnet/kindnet.yaml
  test/e2e/data/kubetest/conformance.yaml
Labels: ignore-for-release

#450 update kube-vip to 0.8.2
  templates/base/kcp.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  templates/clusterclass/kcpt.yaml
Labels: enhancement, lgtm, approved

#464 build(deps): Bump Prism-Go-Client to v0.5.0
  go.mod
  go.sum
Labels: ignore-for-release
