Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-05, with the labels that each got.

#418 Cherry-pick PR #354, #355, #360, and #398 to release-v1.2
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/state.go
  pkg/client/status.go
  pkg/client/status_test.go
  pkg/client/testdata/invalidTestConfigMissingCredentialRef.json
  pkg/client/testdata/validTestCA.pem
  pkg/client/testdata/validTestConfig.json
  pkg/client/testdata/validTestCredentials.json
  pkg/client/testdata/validTestManagerCA.pem
  pkg/client/testdata/validTestManagerCredentials.json
  test/e2e/nutanix_client.go
  test/helpers/prism-go-client/v3/client.go
Labels: lgtm, do-not-merge/hold

#423 Cherry-pick PR #416 to release-v1.2
  controllers/options.go
  controllers/options_test.go
  go.mod
  main.go
Labels: lgtm, approved

#415 Introduce a nutanix prism client cache
  Makefile
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/helpers.go
  controllers/helpers_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  go.mod
  go.sum
  mocks/k8sclient/secret_lister.go
  mocks/k8sclient/secret_namespace_lister.go
  pkg/client/cache.go
  pkg/client/cache_test.go
  pkg/client/client.go
  pkg/client/client_test.go
  test/e2e/nutanix_client.go
Labels: lgtm, approved

#426 Added more generic loops so that adding newer version (v1.30) easier across all tests
  Makefile
  test/e2e/cluster_topology_basic_test.go
  test/e2e/cluster_topology_conformance_test.go
  test/e2e/cluster_topology_k8s_configs.go
  test/e2e/cluster_topology_mega_scale_test.go
  test/e2e/cluster_topology_scale_in_test.go
  test/e2e/cluster_topology_scale_out_test.go
  test/e2e/cluster_topology_scale_up_down_test.go
  test/e2e/cluster_topology_upgrade_test.go
  test/e2e/config/nutanix.yaml
Labels: lgtm, approved

#430 Cherry-pick PR #4013, #406, and #415 to release-v1.2
  .github/workflows/build-dev.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/synopsys-schedule.yaml
  .github/workflows/synopsys.yaml
  Makefile
  api/v1alpha4/nutanixcluster_conversion.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/nutanixmachinetemplate_conversion.go
  api/v1alpha4/nutanixmachinetemplate_types.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  api/v1beta1/nutanixmachine_types.go
  controllers/helpers.go
  controllers/helpers_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  go.mod
  go.sum
  hack/ensure-go.sh
  hack/install-go.sh
  main.go
  mocks/ctlclient/cache_mock.go
  mocks/ctlclient/client_mock.go
  mocks/ctlclient/manager_mock.go
  mocks/k8sclient/cm_informer.go
  mocks/k8sclient/secret_informer.go
  mocks/k8sclient/secret_lister.go
  mocks/k8sclient/secret_namespace_lister.go
  pkg/client/cache.go
  pkg/client/cache_test.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/context/context.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/md_scale_test.go
  test/e2e/mhc_remediations_test.go
  test/e2e/nutanix_client.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
  test/helpers/prism-go-client/v3/client.go
  tools/tools.go
Labels: lgtm, approved

#431 Cherry-pick PR #398 to release-v1.3
  pkg/client/client.go
Labels: lgtm, approved

#432 Cherry-pick PR #416 to release-v1.3
  controllers/options.go
  controllers/options_test.go
  main.go
  main_test.go
Labels: lgtm, approved

#433 Cherry-pick PR #415 to release-v1.3
  .github/workflows/build-dev.yaml
  Makefile
  api/v1alpha4/nutanixcluster_conversion.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/nutanixmachinetemplate_conversion.go
  api/v1alpha4/nutanixmachinetemplate_types.go
  api/v1alpha4/v1alpha4_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  controllers/helpers.go
  controllers/helpers_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  go.mod
  go.sum
  mocks/ctlclient/cache_mock.go
  mocks/ctlclient/client_mock.go
  mocks/ctlclient/manager_mock.go
  mocks/k8sclient/cm_informer.go
  mocks/k8sclient/secret_informer.go
  mocks/k8sclient/secret_lister.go
  mocks/k8sclient/secret_namespace_lister.go
  pkg/client/cache.go
  pkg/client/cache_test.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/context/context.go
  pkg/context/context_test.go
  test/e2e/capx_regression.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/log/log.go
  test/e2e/md_scale_test.go
  test/e2e/mhc_remediations_test.go
  test/e2e/nutanix_client.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
  test/helpers/prism-go-client/v3/client.go
Labels: lgtm, approved

#434 Quote label filters on ci-e2e.sh on main branch
  scripts/ci-e2e.sh
Labels: lgtm, approved

#438 Set OwnerRef on TrustBundle configmaps and add selfhosted E2E test
  .gitignore
  Makefile
  api/v1beta1/conditions.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  test/e2e/clusterctl_move_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/test_helpers.go
Labels: lgtm, approved

#436 Add a watch on CAPI cluster in NutanixMachineReconciler
  Makefile
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  main_test.go
  mocks/k8sapimachinery/interfaces.go
  mocks/k8sclient/informer.go
  mocks/k8sclient/lister.go
  mocks/k8sclient/secret_informer.go
  mocks/k8sclient/secret_lister.go
Labels: bug, lgtm, approved

#440 Cherry-pick PR #438 to release-v1.3
  .gitignore
  Makefile
  api/v1beta1/conditions.go
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  test/e2e/clusterctl_move_test.go
  test/e2e/config/nutanix.yaml
Labels: bug, lgtm, approved

#439 Set Nutanix CCM cipher-suites to fix sweet32 CVE
  templates/ccm/nutanix-ccm.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
Labels: lgtm, approved

#441 Cherry-pick PR #436 to release-v1.3
  Makefile
  controllers/nutanixcluster_controller.go
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  controllers/nutanixmachine_controller_test.go
  go.mod
  go.sum
  mocks/k8sapimachinery/interfaces.go
  mocks/k8sclient/informer.go
  mocks/k8sclient/lister.go
  mocks/k8sclient/secret_informer.go
  mocks/k8sclient/secret_lister.go
Labels: lgtm, approved
