Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-01, with the labels that each got.

#352 Change Cilium options to make E2E test successfully pass
  Makefile
  test/e2e/data/cni/cilium/cilium-no-kubeproxy.yaml
  test/e2e/data/cni/cilium/cilium.yaml
Labels: lgtm, approved

#349 Install a local clusterctl executable and use it in make targets
  Makefile
Labels: ok-to-test, lgtm, approved

#354 fix: improve error handling for Prism Client
  pkg/client/client.go
Labels: ok-to-test, lgtm, approved

#356 feat: Validate prism endpoint is a valid address
  api/v1beta1/nutanixcluster_validate_test.go
  config/crd/kustomization.yaml
  go.mod
  go.sum
Labels: ok-to-test, lgtm, approved

#355 refactor: task status file
  controllers/helpers.go
  controllers/nutanixmachine_controller.go
  pkg/client/state.go
  pkg/client/status.go
  pkg/client/status_test.go
  test/helpers/prism-go-client/v3/client.go
Labels: ok-to-test, lgtm, approved

#361 Update codecov.yml to omit generated code
  .github/codecov.yml
Labels: lgtm, approved

#362 Use codecov token for uploading codecov report
  .github/workflows/build-dev.yaml
Labels: lgtm, approved

#367 Check-in v1.3.0 manifests in test/e2e/data
  Makefile
  metadata.yaml
  test/e2e/config/nutanix.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/ccm-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cm.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/md.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/mhc.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nmt.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm-crs.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm-secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/clusterclass-e2e.yaml
Labels: lgtm, approved

#369 remove CPU/Memory resources settings
  config/manager/manager.yaml
Labels: enhancement, lgtm, approved

#368 removed samples as its redundant with templates
  config/samples/infrastructure_v1alpha4_nutanixcluster.yaml
  config/samples/infrastructure_v1alpha4_nutanixmachine.yaml
  config/samples/infrastructure_v1alpha4_nutanixmachinetemplate.yaml
  config/samples/infrastructure_v1beta1_nutanixcluster.yaml
  config/samples/infrastructure_v1beta1_nutanixmachine.yaml
  config/samples/infrastructure_v1beta1_nutanixmachinetemplate.yaml
Labels: lgtm, approved

#370 removed enable-hostpath-provisioner entry
  templates/base/kcp.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  templates/clusterclass/kcpt.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/clusterclass-e2e.yaml
Labels: lgtm, approved

#371 Add a QuickStart e2e with cluster class
  test/e2e/capx_quick_start_test.go
Labels: lgtm, approved

#373 Update Linter usage in project
  .github/codecov.yml
  .github/release.yaml
  .github/workflows/build-dev.yaml
  .github/workflows/codeql-analysis.yml
  .yamllint
  Makefile
  config/manager/manager.yaml
  config/prometheus/monitor.yaml
  config/rbac/nutanixclustertemplate_editor_role.yaml
  controllers/nutanixcluster_controller_test.go
  controllers/nutanixmachine_controller.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/context/context_test.go
  templates/base-root/nutanix-ccm-secret.yaml
  templates/base-root/secret.yaml
  templates/base/ccm-patch.yaml
  templates/base/cluster-without-topology.yaml
  templates/base/kcp.yaml
  templates/base/kustomization.yaml
  templates/base/nutanix-cluster.yaml
  templates/clusterclass/clusterclass.yaml
  templates/clusterclass/kcpt.yaml
  templates/clusterclass/kustomization.yaml
  templates/clusterclass/nct.yaml
  templates/clusterclass/nmt-cp.yaml
  templates/clusterclass/nmt-md.yaml
  templates/csi/csi-patch.yaml
  templates/csi/kustomization.yaml
  templates/csi/nutanix-csi-crs.yaml
  templates/csi/nutanix-csi-snapshot.yaml
  templates/csi/nutanix-csi-storage.yaml
  templates/topology/ccm-patch.yaml
  templates/topology/cluster-with-topology.yaml
  templates/topology/kustomization.yaml
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/data/cni/calico/calico.yaml
  test/e2e/data/cni/cilium/cilium-no-kubeproxy.yaml
  test/e2e/data/cni/cilium/cilium.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.2.4/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/nutanix-ccm-secret.yaml
  test/e2e/data/infrastructure-nutanix/v1.3.0/base/secret.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/bases/cluster-with-kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1alpha4/no-kubeproxy/cluster-template/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/base/cni-patch.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/no-kubeproxy/cluster-template/kustomization.yaml
  test/e2e/log/log.go
  test/helpers/prism-go-client/v3/client.go
Labels: lgtm, approved

#358 build: migrate to devbox tooling
  .envrc
  .github/workflows/build-dev.yaml
  .github/workflows/release.yaml
  .github/workflows/synopsys-schedule.yaml
  .github/workflows/synopsys.yaml
  .github/workflows/trivy-scan.yaml
  .gitignore
  Makefile
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachinetemplates.yaml
  devbox.json
  devbox.lock
  docs/developer_workflow.md
  go.mod
  hack/ensure-go.sh
  hack/flakes/flake.lock
  hack/flakes/flake.nix
  hack/install-go.sh
  scripts/ci-e2e.sh
  scripts/go_install.sh
  test-cluster-without-topology.mk
Labels: lgtm, approved
