Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-02, with the labels that each got.

#377 move to new blackduck synopsys-action
  .github/workflows/synopsys-schedule.yaml
  .github/workflows/synopsys.yaml
Labels: ignore-for-release, lgtm, approved

#360 refactor: client.go file helper methods
  api/v1beta1/nutanixcluster_types.go
  api/v1beta1/nutanixcluster_types_test.go
  controllers/helpers.go
  controllers/nutanixcluster_controller.go
  pkg/client/client.go
  pkg/client/client_test.go
  pkg/client/testdata/invalidTestConfigMissingCredentialRef.json
  pkg/client/testdata/validTestCA.pem
  pkg/client/testdata/validTestConfig.json
  pkg/client/testdata/validTestCredentials.json
  pkg/client/testdata/validTestManagerCA.pem
  pkg/client/testdata/validTestManagerCredentials.json
  test/e2e/nutanix_client.go
Labels: lgtm, approved

#379 Change target Github branches for Github Actions
  .github/workflows/build-dev.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/synopsys.yaml
Labels: lgtm, approved

#380 Cherry-pick PR #379 to release-v1.3
  .github/workflows/build-dev.yaml
  .github/workflows/codeql-analysis.yml
  .github/workflows/synopsys.yaml
Labels: lgtm, approved

#375 Cherry-pick PR #369 to release-v1.3
  config/manager/manager.yaml
Labels: ok-to-test, lgtm, approved

#381 [WIP] renamed kct to use clusterclass name
  templates/cluster-template-clusterclass.yaml
  templates/clusterclass/clusterclass.yaml
  templates/clusterclass/kct.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/clusterclass-e2e.yaml
Labels: do-not-merge/work-in-progress, lgtm, approved
