Repository nutanix-cloud-native/cluster-api-provider-nutanix, pull requests merged in 2024-03, with the labels that each got.

#382 Add support for Kubernetes v1.29 clusters
  templates/base/kcp.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-csi.yaml
  templates/cluster-template.yaml
  templates/clusterclass/kcpt.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/cluster-template-csi/kcp.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/clusterclass-e2e.yaml
Labels: lgtm, approved

#384 removed namespace for clusterclass and cluster with topology
  templates/base-root/kustomization.yaml
  templates/cluster-template-clusterclass.yaml
  templates/cluster-template-topology.yaml
  templates/clusterclass/kustomization.yaml
  templates/topology/kustomization.yaml
  test/e2e/data/infrastructure-nutanix/v1beta1/clusterclass-e2e.yaml
Labels: lgtm, approved

#383 Update component versions for CAPI, Kind, and other dependencies
  .github/workflows/build-dev.yaml
  .golangci.yaml
  Makefile
  api/v1alpha4/nutanixcluster_conversion.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_conversion.go
  api/v1alpha4/nutanixmachine_types.go
  api/v1alpha4/nutanixmachinetemplate_conversion.go
  api/v1alpha4/nutanixmachinetemplate_types.go
  api/v1alpha4/v1alpha4_test.go
  api/v1alpha4/zz_generated.deepcopy.go
  api/v1beta1/nutanixcluster_validate_test.go
  api/v1beta1/zz_generated.deepcopy.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclustertemplates.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachinetemplates.yaml
  config/default/manager_auth_proxy_patch.yaml
  config/rbac/role.yaml
  controllers/nutanixcluster_controller.go
  controllers/nutanixmachine_controller.go
  devbox.json
  devbox.lock
  go.mod
  go.sum
  main.go
  main_test.go
  mocks/ctlclient/cache_mock.go
  mocks/ctlclient/client_mock.go
  mocks/ctlclient/manager_mock.go
  mocks/k8sclient/cm_informer.go
  mocks/k8sclient/secret_informer.go
  package/docker/Dockerfile
  pkg/client/status.go
  pkg/context/context.go
  pkg/context/context_test.go
  test/e2e/capx_quick_start_test.go
  test/e2e/cluster_upgrade_test.go
  test/e2e/clusterctl_upgrade_test.go
  test/e2e/config/nutanix.yaml
  test/e2e/csi_test.go
  test/e2e/data/shared/metadata.yaml
  test/e2e/e2e_suite_test.go
  test/e2e/md_scale_test.go
  test/e2e/mhc_remediations_test.go
  test/e2e/projects_test.go
  test/e2e/test_helpers.go
Labels: breaking-change

#388 Mark v1alpha4 CRDs as Deprecated and Unserved
  api/v1alpha4/doc.go
  api/v1alpha4/nutanixcluster_types.go
  api/v1alpha4/nutanixmachine_types.go
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixclusters.yaml
  config/crd/bases/infrastructure.cluster.x-k8s.io_nutanixmachines.yaml
  main.go
Labels: breaking-change

#401 add devbox context for ko in trivy workflow
  .github/workflows/trivy-scan.yaml
Labels: ignore-for-release, lgtm, approved
